### PR TITLE
clean-up

### PR DESCRIPTION
**Pull request by joshuaaguilar20**
Hey got it all working, Id love for you to check out the changes and let me know what you think.  Here is  a list of changes I made to clean things up. I added a few kill commands to end processes, but left all the functions the same. 

--Removed App File and renamed to conventional Index.js ( following Node Js Docs Recommendations) 
--Moved Passport and JWT token to Seperate Files So it Clear how the Server is Running. 
--Removed The server folder as this is done in index.js 
--moved All documents to documents folder and left readME in root to follow convention 
-- created middleware folder for all middleware functions so they can be reused throughout the codebase
--Removed Server file and updated Scripts to run from index.js as this is the typical starting point for node application 
--Created test folder for Backend testing* 
--Added Rootpath for all unknown routes to send users back to home if they request unused URL 
--

I did a pull request I have not been able to test everything fully yet as there is a lot of unused code in the backend I wanted to breakup into a playground folder. let me know what you guys think. Its currently passing all testing that I have seen .

@TODO 

-move twilo to services folder* 
-confirm bcrypt  is storing passports correctly hashed
-clean up controllers and commented out code

### CODE REVIEW

**Comment by joshuaaguilar20** [comment]
I just installed Circle CI checks so I do not think it ran for the above but I just ran it in circle CI in it passed we need to set up the backend checks as well!

**Comment by joshuaaguilar20** [comment]
I just installed GH Checks for Circle CI So this Should be Running. I added branch protection and everything 
odd its not running

**Comment by Wolfy64** [comment]
I just setup CI and I didn't wrote test yet for the FE but if you want to write.
I already added branch protection on `master` and `development` maybe it's for that you didn't pass.
You can't push directly on thoses branch you to create your branch at your name then you have to do a pull request on the `development` branch that will run remotely CircleCI

**Comment by joshuaaguilar20** [comment]
David,

I can push it to the dev branch as well. I made my dev branch as well. Did
u see the clean up? It's all running on my pc and I want to write some more
test and get the system up and running. Who built this backend? I just need
to chat with u or who ever built it for like 10 minutes and we could prolly
finish most of the backend features in a week. Ps I got the job man!!!

**Comment by Wolfy64** [comment]
Congrats for your job at IBM !! 🎉
Check your message on Slack 🙂
Most of the backend is from Henry @thMthMnky I would love to know more about it as well

**Pull request closed without merging**
